name: Trivy Scan and SBOM Generation

on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main

jobs:
    trivy-scan:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Set up Trivy
          uses: aquasecurity/trivy-action@main
          with:
            scan-type: 'fs'
            format: 'cyclonedx'
            output: 'sbom.xml'
            exit-code: '0'
            ignore-unfixed: true

        - name: Upload SBOM
          uses: actions/upload-artifact@v3
          with:
            name: sbom
            path: sbom.xml
