name: Trivy Scan and SBOM Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    trivy-scan:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Trivy
          uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
          with:
            scan-type: 'fs'
            format: 'table'
            exit-code: '0'
            ignore-unfixed: true

        - name: Run Trivy in GitHub SBOM mode and submit results to Dependency Graph
          uses: aquasecurity/trivy-action@0.28.0
          with:
            scan-type: 'fs'
            format: 'github'
            output: 'dependency-results.sbom.json'
            image-ref: '.'
            github-pat: ${{ secrets.GITHUB_TOKEN }} # or ${{ secrets.github_pat_name }} if you're using a PAT

        - name: Upload SBOM
          uses: actions/upload-artifact@v3
          with:
            name: sbom
            path: sbom.xml
